name: testing_new_things
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  internet_state_manager:
    git:
      url: https://github.com/MAlazhariy/internet_state_manager.git
      ref: v1.0.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
